# Generated by Django 4.2.9 on 2025-01-21 09:48

import ckeditor_uploader.fields
from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='Game title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Game slug')),
                ('description', models.CharField(max_length=255, verbose_name='Game Description')),
                ('iframeTitle', models.CharField(max_length=50, verbose_name='iframeTitle')),
                ('iframeDescription', models.CharField(max_length=255, verbose_name='iframeDescription')),
                ('thumbnail', models.FileField(default='/avatars/default.png', upload_to=game.models.get_file_path)),
                ('GamePageUrl', models.CharField(max_length=50, verbose_name='GamePageUrl')),
                ('iframePageUrl', models.CharField(max_length=100, verbose_name='iframePageUrl')),
                ('recommend', models.IntegerField(default=0, verbose_name='推荐')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='update_time')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('whatis', ckeditor_uploader.fields.RichTextUploadingField()),
                ('HowtoPlay', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('site_url', models.CharField(max_length=32, verbose_name='站点域名')),
                ('site_name', models.CharField(max_length=64, verbose_name='站点名称')),
                ('logo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('title', models.CharField(max_length=64, verbose_name='SEO标题')),
                ('description', models.CharField(max_length=255, verbose_name='Game Description')),
            ],
        ),
    ]
