# Generated by Django 4.2.9 on 2025-02-25 13:46

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='游戏名称')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='游戏网址')),
                ('description', models.CharField(max_length=1024, verbose_name='游戏描述')),
                ('thumbnail', models.FileField(upload_to=game.models.get_file_path, verbose_name='游戏图片')),
                ('iframeUrl', models.CharField(max_length=512, verbose_name='IFRAME')),
                ('recommend', models.IntegerField(choices=[(0, '[0]不推荐'), (1, '[1]左边推荐'), (2, '[2]右边推荐'), (3, '[3]主游戏'), (4, '[4]顶部推荐')], default=0, verbose_name='推荐等级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='update_time')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('whatis', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('HowtoPlay', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('source', models.CharField(default='', max_length=128, verbose_name='游戏来源')),
                ('is_checked', models.BooleanField(default=False, verbose_name='是否发布')),
            ],
        ),
        migrations.CreateModel(
            name='Pachong',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='游戏名称')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='游戏描述')),
                ('source', models.CharField(blank=True, max_length=128, null=True, verbose_name='游戏来源')),
                ('is_caiji', models.BooleanField(default=False, verbose_name='是否已采集')),
                ('is_publish', models.BooleanField(default=False, verbose_name='是否已发布')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('site_url', models.CharField(max_length=64, verbose_name='站点域名')),
                ('site_name', models.CharField(max_length=128, verbose_name='站点名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=game.models.get_file_path)),
                ('title', models.CharField(max_length=128, verbose_name='SEO标题')),
                ('description', models.CharField(max_length=512, verbose_name='站点描述')),
                ('aboutus', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='关于我们')),
                ('copyright', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='copyright')),
                ('contactus', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='contact us')),
                ('Privacypolicy', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Privacy policy')),
                ('Termofuse', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Term of use')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=512, verbose_name='游戏问题')),
                ('answer', models.CharField(blank=True, max_length=512, verbose_name='问题答案')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='所属游戏')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.site', verbose_name='所属站点'),
        ),
    ]
