# Generated by Django 4.2.9 on 2025-03-01 10:33

from django.db import migrations, models
import django_ckeditor_5.fields
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=game.models.get_file_path, verbose_name='游戏图片'),
        ),
        migrations.AlterField(
            model_name='site',
            name='Termofuse',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Term of use'),
        ),
    ]
