# Generated by Django 4.2.9 on 2025-01-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
