# Generated by Django 4.2.9 on 2025-03-01 10:36

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_thumbnail_alter_site_termofuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.FileField(default='/avatars/default.png', upload_to=game.models.get_file_path, verbose_name='游戏图片'),
        ),
    ]
