# Generated by Django 4.2.9 on 2025-01-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_site_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='iframePageUrl',
            new_name='iframeUrl',
        ),
    ]
