# Generated by Django 4.2.9 on 2025-01-16 21:37

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_iframepageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='HowtoPlay',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='whatis',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
