# Generated by Django 4.2.9 on 2025-01-16 22:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_howtoplay_alter_game_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='HowtoPlay',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='whatis',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
