# Generated by Django 4.2.9 on 2025-01-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_iframepageurl_game_iframeurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='GamePageUrl',
        ),
    ]
