# Generated by Django 4.2.9 on 2025-01-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_gamepageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='iframeDescription',
        ),
        migrations.RemoveField(
            model_name='game',
            name='iframeTitle',
        ),
        migrations.AlterField(
            model_name='game',
            name='iframeUrl',
            field=models.CharField(max_length=100, verbose_name='游戏iframe链接'),
        ),
    ]
