# Generated by Django 4.2.9 on 2025-01-22 11:48

import ckeditor_uploader.fields
from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_iframedescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='HowtoPlay',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=255, verbose_name='游戏描述'),
        ),
        migrations.AlterField(
            model_name='game',
            name='recommend',
            field=models.IntegerField(default=0, verbose_name='推荐等级'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='游戏网址'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.FileField(default='/avatars/default.png', upload_to=game.models.get_file_path, verbose_name='游戏图片地址'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=64, verbose_name='游戏名称'),
        ),
        migrations.AlterField(
            model_name='game',
            name='whatis',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
