# Generated by Django 4.2.9 on 2025-01-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_howtoplay_alter_game_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questiones',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=200, verbose_name='游戏问题')),
                ('answer', models.CharField(blank=True, max_length=200, verbose_name='问题答案')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='所属游戏')),
            ],
        ),
    ]
