# Generated by Django 4.2.9 on 2025-01-25 10:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_questiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='Privacypolicy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='copyright'),
        ),
        migrations.AddField(
            model_name='site',
            name='Termofuse',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='copyright'),
        ),
        migrations.AddField(
            model_name='site',
            name='aboutus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='关于我们'),
        ),
        migrations.AddField(
            model_name='site',
            name='contactus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='copyright'),
        ),
        migrations.AddField(
            model_name='site',
            name='copyright',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='copyright'),
        ),
    ]
