# Generated by Django 4.2.9 on 2025-01-25 10:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_site_privacypolicy_site_termofuse_site_aboutus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='Privacypolicy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='site',
            name='Termofuse',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Term of use'),
        ),
        migrations.AlterField(
            model_name='site',
            name='contactus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contact us'),
        ),
    ]
