# Generated by Django 4.2.9 on 2025-01-26 11:59

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_site_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(upload_to=game.models.get_file_path),
        ),
    ]
