# Generated by Django 4.2.9 on 2025-01-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_site_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='recommend',
            field=models.IntegerField(choices=[(0, '不推荐'), (1, '左边推荐'), (2, '右边推荐'), (3, '主推荐'), (4, '顶部导航')], default=0, verbose_name='推荐等级'),
        ),
    ]
