# Generated by Django 4.2.9 on 2025-01-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_game_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='recommend',
            field=models.IntegerField(choices=[(0, '一般游戏'), (1, '左边推荐'), (2, '右边推荐'), (3, '主游戏'), (4, '顶部推荐')], default=0, verbose_name='推荐等级'),
        ),
    ]
