# Generated by Django 4.2.9 on 2025-01-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_game_recommend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questiones',
            new_name='Questions',
        ),
        migrations.AlterField(
            model_name='game',
            name='recommend',
            field=models.IntegerField(choices=[(0, '[0]不推荐'), (1, '[1]左边推荐'), (2, '[2]右边推荐'), (3, '[3]主游戏'), (4, '[4]顶部推荐')], default=0, verbose_name='推荐等级'),
        ),
    ]
