# Generated by Django 4.2.9 on 2025-01-29 17:24

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_questiones_questions_alter_game_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='iframeUrl',
            field=models.CharField(max_length=100, verbose_name='Iframe链接'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.FileField(default='/avatars/default.png', upload_to=game.models.get_file_path, verbose_name='游戏图片'),
        ),
    ]
