# Generated by Django 4.2.9 on 2025-01-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_iframeurl_alter_game_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='iframeUrl',
            field=models.CharField(max_length=100, verbose_name='Iframe'),
        ),
    ]
