# Generated by Django 4.2.9 on 2025-02-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_game_iframeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.CharField(max_length=255, verbose_name='站点描述'),
        ),
    ]
