# Generated by Django 4.2.9 on 2025-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_site_site_name_alter_site_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=512, verbose_name='游戏描述'),
        ),
    ]
