# Generated by Django 4.2.9 on 2025-02-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_game_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pachong',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='游戏名称')),
                ('description', models.TextField(max_length=512, verbose_name='游戏描述')),
                ('source', models.CharField(max_length=128, verbose_name='游戏来源')),
                ('is_caiji', models.BooleanField(default=False, verbose_name='是否已采集')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='source',
            field=models.CharField(default='', max_length=128, verbose_name='游戏来源'),
        ),
    ]
