# Generated by Django 4.2.9 on 2025-02-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_pachong_game_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pachong',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='游戏描述'),
        ),
        migrations.AlterField(
            model_name='pachong',
            name='source',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='游戏来源'),
        ),
        migrations.AlterField(
            model_name='pachong',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='游戏名称'),
        ),
    ]
