# Generated by Django 4.2.9 on 2025-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_pachong_description_alter_pachong_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
    ]
