# Generated by Django 4.2.9 on 2025-02-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_game_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='pachong',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='是否已发布'),
        ),
    ]
