# Generated by Django 4.2.9 on 2025-02-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_alter_game_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='游戏描述'),
        ),
    ]
