# Generated by Django 4.2.9 on 2025-02-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_game_iframeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='iframeUrl',
            field=models.CharField(max_length=256, verbose_name='IFRAME'),
        ),
    ]
