# Generated by Django 4.2.9 on 2025-02-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_alter_game_iframeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='iframeUrl',
            field=models.CharField(max_length=512, verbose_name='IFRAME'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.CharField(max_length=512, verbose_name='站点描述'),
        ),
    ]
