# Generated by Django 4.2.9 on 2025-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_alter_questions_answer_alter_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='sites', to='game.game', verbose_name='关联游戏'),
        ),
    ]
