# Generated by Django 4.2.9 on 2025-02-23 11:37

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_site_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.site', verbose_name='所属站点'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.FileField(upload_to=game.models.get_file_path, verbose_name='游戏图片'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.get_file_path),
        ),
    ]
